substitutions:
  heatpump_climate_room_0: Termostato habitación 0
  heatpump_climate_room_1: Termostato habitación 1
  heatpump_climate_room_2: Termostato habitación 2
  heatpump_climate_room_3: Termostato habitación 3
  heatpump_climate_room_4: Termostato habitación 4
  heatpump_climate_room_5: Termostato habitación 5
  heatpump_climate_room_6: Termostato habitación 6
  heatpump_climate_room_7: Termostato habitación 7

  wifi_signal_proc: Señal WiFi %
  wifi_signal_db: Señal WiFi dB
  esp_ip: IP del ESP
  internal_esp_temperature: Temperatura Interna ESP
  esp_sidd: SSID del ESP
  uptime: Tiempo en funcionamiento del ESP
  esp_version: Versión de ESP