substitutions:
  heatpump_climate_room_0: Thermostat de la pièce 0
  heatpump_climate_room_1: Thermostat de la pièce 1
  heatpump_climate_room_2: Thermostat de la pièce 2
  heatpump_climate_room_3: Thermostat de la pièce 3
  heatpump_climate_room_4: Thermostat de la pièce 4
  heatpump_climate_room_5: Thermostat de la pièce 5
  heatpump_climate_room_6: Thermostat de la pièce 6
  heatpump_climate_room_7: Thermostat de la pièce 7

  wifi_signal_proc: Signal Wifi %
  wifi_signal_db: Signal Wifi dB
  esp_ip: ESP IP
  internal_esp_temperature: Temp interne ESP
  esp_sidd: ESP SSID
  uptime: ESP Uptime
  esp_version: ESP Version