substitutions:
  heatpump_climate_room_0: Kamer thermostaat 0
  heatpump_climate_room_1: Kamer thermostaat 1
  heatpump_climate_room_2: Kamer thermostaat 2
  heatpump_climate_room_3: Kamer thermostaat 3
  heatpump_climate_room_4: Kamer thermostaat 4
  heatpump_climate_room_5: Kamer thermostaat 5
  heatpump_climate_room_6: Kamer thermostaat 6
  heatpump_climate_room_7: Kamer thermostaat 7

  wifi_signal_proc: WiFi Signaal %
  wifi_signal_db: WiFi Signaal dB
  esp_ip: Esp IP
  internal_esp_temperature: Esp Interne temperatuur
  esp_sidd: Esp SSID
  uptime: Esp Uptime
  esp_version: Esp Versie