substitutions:
  name: ecodan-thermostat
  friendlyName: Ecodan thermostat

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

ota:
  - platform: esphome
#  password: !secret heatpump_ota_password

api:
  reboot_timeout: 0s
#  encryption:
#    key: !secret heatpump_encryption_key

external_components:
- source:
    type: local
    path: components
  components: [ ecodan ]

packages:
 esp32: !include confs/esp32s3.yaml
 thermostat-room-0: !include { file: confs/thermostat-room.yaml, vars: { room_identifier: 0, room_name: "Room 1" } }
 thermostat-room-1: !include { file: confs/thermostat-room.yaml, vars: { room_identifier: 1, room_name: "Room 2" } }
# up to 8 thermostats can be defined. 0-7.

# change language labels to -en for English or -nl for Dutch
 substitutions: !include confs/ecodan-labels-en.yaml
 dbg: !include confs/debug.yaml
 wifi: !include confs/wifi.yaml

# external_components:
#   - source: github://gekkekoe/esphome-ecodan-hp@main
#     components: [ ecodan ]
#     refresh: always

# packages:
#   remote_package:
#     url: https://github.com/gekkekoe/esphome-ecodan-hp/
#     ref: main
#     refresh: always
#     files: [ 
#             confs/base.yaml,        # required
#             confs/esp32s3-proxy2.yaml,     # confs/esp32.yaml, for regular board
#             confs/zone1.yaml,
#             ## enable if you want to use zone 2
#             #confs/zone2.yaml,
#             ## enable label language file
#             confs/ecodan-labels-en.yaml,
#             #confs/ecodan-labels-nl.yaml,
#             #confs/ecodan-labels-it.yaml,
#             #confs/ecodan-labels-fr.yaml,
#             confs/server-control.yaml,
#             #confs/debug.yaml,
#             ## enable this to monitor WiFi status with ESP in-built LED
#             #confs/status_led.yaml,
#             ## enable this to monitor status with custom led colors, uses https://github.com/esphome/esphome/pull/5814
#             #confs/status_led_rgb.yaml,
#             confs/wifi.yaml
#            ]

# enable logger
logger:
  baud_rate: 115200
  logs:
    esp32.preferences: DEBUG
    sensor: DEBUG
    text_sensor: DEBUG
    binary_sensor: DEBUG
    switch: DEBUG
    button: DEBUG
    number: DEBUG
    climate: DEBUG
    component: DEBUG
    ecodan.component: DEBUG

# Enable Web server.
web_server:
  port: 80
  #ota: true

ecodan:
  id: ecodan_instance
  uart_id: uart_ecodan

